version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_ai_poc
    environment:
      POSTGRES_DB: aipoc
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
